# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Sistema')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
                'verbose_name': 'Sistema',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.CharField(max_length=50, verbose_name='Resumo')),
                ('casa_legislativa', models.CharField(max_length=200, verbose_name='Casa Legislativa')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.Sistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'ordering': ['data_criacao'],
                'verbose_name_plural': 'Solicitações de Novos Serviços',
                'verbose_name': 'Solicitação de Novo Serviço',
            },
        ),
    ]
