# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20160531_1453'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Sistema')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.CharField(max_length=50, verbose_name='Resumo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Sistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.UsuarioExterno')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.RemoveField(
            model_name='servico',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
