# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=100, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=100, verbose_name='Telefone')),
                ('endereco_web', models.URLField(blank=True, max_length=100, verbose_name='HomePage')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Casa Legislativa',
                'verbose_name_plural': 'Casas Legislativas',
            },
        ),
        migrations.CreateModel(
            name='Subsecretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Subsecretaria',
                'ordering': ('nome', 'sigla'),
                'verbose_name_plural': 'Subsecretarias',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIXO', 'FIXO'), ('CELULAR', 'CELULAR')], max_length=7, verbose_name='Tipo Telefone')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('principal', models.CharField(choices=[(None, '----'), (False, 'Não'), (True, 'Sim')], max_length=10, verbose_name='Telefone Principal?')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário')),
                ('nome_completo', models.CharField(max_length=128, verbose_name='Nome Completo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última atualização')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado?')),
                ('conveniado', models.BooleanField(default=False)),
                ('responsavel', models.BooleanField(default=False)),
                ('rg', models.CharField(max_length=9, null=True, verbose_name='RG')),
                ('cpf', models.CharField(default='00000000000', max_length=11, verbose_name='CPF')),
                ('cargo', models.CharField(default='--------', max_length=30, verbose_name='Cargo')),
                ('vinculo', models.CharField(choices=[('Tercerizado', 'Tercerizado'), ('Efetivo', 'Efetivo'), ('Contratado', 'Contratado')], default='--------', max_length=30, verbose_name='Vinculo')),
                ('casa_legislativa', models.CharField(default='--------', max_length=30, verbose_name='Casa Legislativa')),
                ('primeiro_telefone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_telefone', to='usuarios.Telefone')),
                ('segundo_telefone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segundo_telefone', to='usuarios.Telefone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
