# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=100, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=100, verbose_name='Telefone')),
                ('endereco_web', models.URLField(blank=True, max_length=100, verbose_name='HomePage')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Casa Legislativa',
                'verbose_name_plural': 'Casas Legislativas',
            },
        ),
        migrations.CreateModel(
            name='Subsecretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Subsecretaria',
                'verbose_name_plural': 'Subsecretarias',
            },
        ),
        migrations.CreateModel(
            name='UsuarioExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nome de Usuário')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('nome_completo', models.CharField(max_length=128, verbose_name='Nome Completo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=25, null=True, verbose_name='RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('endereco', models.CharField(max_length=256, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('habilitado', models.CharField(choices=[(True, 'Sim'), (False, 'Não')], max_length=3, verbose_name='Habilitado?')),
                ('casa_legislativa', models.ManyToManyField(to='usuarios.CasaLegislativa', verbose_name='Casa Legislativa')),
            ],
            options={
                'verbose_name': 'Usuário Externo',
                'verbose_name_plural': 'Usuários Externo',
            },
        ),
        migrations.CreateModel(
            name='UsuarioInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nome de Usuário')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('nome_completo', models.CharField(max_length=128, verbose_name='Nome Completo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=25, null=True, verbose_name='RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('endereco', models.CharField(max_length=256, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('matricula', models.CharField(max_length=25, verbose_name='Matrícula')),
                ('subsecretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Subsecretaria', verbose_name='Subsecretaria')),
            ],
            options={
                'verbose_name': 'Usuário Interno',
                'verbose_name_plural': 'Usuários Interno',
            },
        ),
    ]
