# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:27
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name=u'CasaLegislativa',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'nome', models.CharField(max_length=100, verbose_name=u'Nome')),
                (u'sigla', models.CharField(max_length=100, verbose_name=u'Sigla')),
                (u'endereco', models.CharField(max_length=100, verbose_name=u'Endereço')),
                (u'cep', models.CharField(max_length=100, verbose_name=u'CEP')),
                (u'municipio', models.CharField(max_length=100, verbose_name=u'Município')),
                (u'uf', models.CharField(choices=[(u'AC', u'Acre'), (u'AL', u'Alagoas'), (u'AP', u'Amapá'), (u'AM', u'Amazonas'), (u'BA', u'Bahia'), (u'CE', u'Ceará'), (u'DF', u'Distrito Federal'), (u'ES', u'Espírito Santo'), (u'GO', u'Goiás'), (u'MA', u'Maranhão'), (u'MT', u'Mato Grosso'), (u'MS', u'Mato Grosso do Sul'), (u'MG', u'Minas Gerais'), (u'PR', u'Paraná'), (u'PB', u'Paraíba'), (u'PA', u'Pará'), (u'PE', u'Pernambuco'), (u'PI', u'Piauí'), (u'RJ', u'Rio de Janeiro'), (u'RN', u'Rio Grande do Norte'), (u'RS', u'Rio Grande do Sul'), (u'RO', u'Rondônia'), (u'RR', u'Roraima'), (u'SC', u'Santa Catarina'), (u'SE', u'Sergipe'), (u'SP', u'São Paulo'), (u'TO', u'Tocantins'), (u'EX', u'Exterior')], max_length=100, verbose_name=u'UF')),
                (u'telefone', models.CharField(blank=True, max_length=100, verbose_name=u'Telefone')),
                (u'endereco_web', models.URLField(blank=True, max_length=100, verbose_name=u'HomePage')),
                (u'email', models.EmailField(blank=True, max_length=100, verbose_name=u'E-mail')),
            ],
            options={
                u'verbose_name': u'Casa Legislativa',
                u'verbose_name_plural': u'Casas Legislativas',
            },
        ),
        migrations.CreateModel(
            name=u'Subsecretaria',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'nome', models.CharField(max_length=100, null=True, verbose_name=u'Nome')),
                (u'sigla', models.CharField(max_length=10, null=True, verbose_name=u'Sigla')),
            ],
            options={
                u'verbose_name': u'Subsecretaria',
                u'verbose_name_plural': u'Subsecretarias',
            },
        ),
        migrations.CreateModel(
            name=u'UsuarioExterno',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'username', models.CharField(max_length=50, verbose_name=u'Nome de Usuário')),
                (u'cargo', models.CharField(max_length=120, verbose_name=u'Cargo')),
                (u'nome_completo', models.CharField(max_length=128, verbose_name=u'Nome Completo')),
                (u'data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                (u'sexo', models.CharField(choices=[(u'M', u'Masculino'), (u'F', u'Feminino')], max_length=1, verbose_name=u'Sexo')),
                (u'cpf', models.CharField(max_length=11, verbose_name=u'CPF')),
                (u'rg', models.CharField(blank=True, max_length=25, null=True, verbose_name=u'RG')),
                (u'email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=u'Email')),
                (u'endereco', models.CharField(max_length=256, verbose_name=u'Endereço')),
                (u'telefone', models.CharField(max_length=20, verbose_name=u'Telefone')),
                (u'habilitado', models.CharField(choices=[(True, u'Sim'), (False, u'Não')], max_length=3, verbose_name=u'Habilitado?')),
                (u'casa_legislativa', models.ManyToManyField(to=u'usuarios.CasaLegislativa', verbose_name=u'Casa Legislativa')),
            ],
            options={
                u'verbose_name': u'Usuário Externo',
                u'verbose_name_plural': u'Usuários Externo',
            },
        ),
        migrations.CreateModel(
            name=u'UsuarioInterno',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'username', models.CharField(max_length=50, verbose_name=u'Nome de Usuário')),
                (u'cargo', models.CharField(max_length=120, verbose_name=u'Cargo')),
                (u'nome_completo', models.CharField(max_length=128, verbose_name=u'Nome Completo')),
                (u'data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                (u'sexo', models.CharField(choices=[(u'M', u'Masculino'), (u'F', u'Feminino')], max_length=1, verbose_name=u'Sexo')),
                (u'cpf', models.CharField(max_length=11, verbose_name=u'CPF')),
                (u'rg', models.CharField(blank=True, max_length=25, null=True, verbose_name=u'RG')),
                (u'email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=u'Email')),
                (u'endereco', models.CharField(max_length=256, verbose_name=u'Endereço')),
                (u'telefone', models.CharField(max_length=20, verbose_name=u'Telefone')),
                (u'matricula', models.CharField(max_length=25, verbose_name=u'Matrícula')),
                (u'subsecretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.Subsecretaria', verbose_name=u'Subsecretaria')),
            ],
            options={
                u'verbose_name': u'Usuário Interno',
                u'verbose_name_plural': u'Usuários Interno',
            },
        ),
    ]
