# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioexterno',
            options={'verbose_name': 'Usuário Externo', 'verbose_name_plural': 'Usuários Externos'},
        ),
        migrations.AlterModelOptions(
            name='usuariointerno',
            options={'verbose_name': 'Usuário Interno', 'verbose_name_plural': 'Usuários Internos'},
        ),
    ]
