# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 16:57
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name=u'usuarioexterno',
            options={u'verbose_name': u'Usuário Externo', u'verbose_name_plural': u'Usuários Externos'},
        ),
        migrations.AlterModelOptions(
            name=u'usuariointerno',
            options={u'verbose_name': u'Usuário Interno', u'verbose_name_plural': u'Usuários Internos'},
        ),
    ]
