# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 17:50
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0002_auto_20160531_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name=u'subsecretaria',
            options={u'ordering': (u'nome', u'sigla'), u'verbose_name': u'Subsecretaria', u'verbose_name_plural': u'Subsecretarias'},
        ),
        migrations.AlterField(
            model_name=u'casalegislativa',
            name=u'email',
            field=models.EmailField(max_length=100, verbose_name=u'E-mail'),
        ),
    ]
