# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160531_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsecretaria',
            options={'ordering': ('nome', 'sigla'), 'verbose_name': 'Subsecretaria', 'verbose_name_plural': 'Subsecretarias'},
        ),
        migrations.AlterField(
            model_name='casalegislativa',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
    ]
