# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20160531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuarioexterno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuariointerno',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
