# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 17:53
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0003_auto_20160531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'casalegislativa',
            name=u'email',
            field=models.EmailField(blank=True, max_length=100, verbose_name=u'E-mail'),
        ),
        migrations.AlterField(
            model_name=u'usuarioexterno',
            name=u'email',
            field=models.EmailField(max_length=254, verbose_name=u'Email'),
        ),
        migrations.AlterField(
            model_name=u'usuariointerno',
            name=u'email',
            field=models.EmailField(default=u'a@a.com', max_length=254, verbose_name=u'Email'),
            preserve_default=False,
        ),
    ]
