# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:56
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0004_auto_20160531_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name=u'usuariointerno',
            name=u'subsecretaria',
        ),
        migrations.DeleteModel(
            name=u'UsuarioInterno',
        ),
    ]
