# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 12:47
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (u'servicos', u'0004_auto_20160602_0947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (u'usuarios', u'0005_auto_20160601_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Usuario',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'username', models.CharField(max_length=50, verbose_name=u'Nome de Usuário')),
                (u'password', models.CharField(max_length=20, verbose_name=u'Senha')),
                (u'nome_completo', models.CharField(max_length=128, verbose_name=u'Nome Completo')),
                (u'data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                (u'data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                (u'email', models.EmailField(max_length=254, verbose_name=u'Email')),
                (u'habilitado', models.CharField(choices=[(True, u'Sim'), (False, u'Não')], default=u'Sim', max_length=3, verbose_name=u'Habilitado?')),
                (u'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                u'verbose_name': u'Usuário',
                u'verbose_name_plural': u'Usuários',
            },
        ),
        migrations.RemoveField(
            model_name=u'usuarioexterno',
            name=u'casa_legislativa',
        ),
        migrations.DeleteModel(
            name=u'UsuarioExterno',
        ),
    ]
