# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 13:21
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0009_remove_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'usuario',
            name=u'email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=u'Email'),
        ),
    ]
