# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 13:51
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0010_auto_20160602_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'usuario',
            name=u'username',
            field=models.CharField(max_length=50, unique=True, verbose_name=u'Nome de Usuário'),
        ),
    ]
