# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20160602_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('can_change_habilitado', 'User can change habilitado field'), ('can_change_responsavel', 'User can change habilitado field')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
