# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20160603_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('can_change_conveniado', 'User can change habilitado field'), ('can_change_responsave', 'User can change habilitado field')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
