# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20160602_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefoneUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('FIXO', 'FIXO'), ('CELULAR', 'CELULAR')], max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
