# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 14:15
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0012_auto_20160602_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'TelefoneUsuario',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'ddd', models.CharField(max_length=2)),
                (u'numero', models.CharField(max_length=10)),
                (u'tipo', models.CharField(choices=[(u'FIXO', u'FIXO'), (u'CELULAR', u'CELULAR')], max_length=7)),
                (u'usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.Usuario')),
            ],
            options={
                u'verbose_name': u'Telefone',
                u'verbose_name_plural': u'Telefones',
            },
        ),
    ]
