# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_telefoneusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIXO', 'FIXO'), ('CELULAR', 'CELULAR')], max_length=7, verbose_name='Tipo Telefone')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('principal', models.CharField(choices=[(False, 'Não'), (True, 'Sim')], max_length=10, verbose_name='Telefone Principal?')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.RemoveField(
            model_name='telefoneusuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='--------', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='casa_legislativa',
            field=models.CharField(default='--------', max_length=30, verbose_name='Casa Legislativa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=9, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(choices=[('Tercerizado', 'Tercerizado'), ('Efetivo', 'Efetivo'), ('Contratado', 'Contratado')], default='--------', max_length=10, verbose_name='Vinculo'),
        ),
        migrations.DeleteModel(
            name='TelefoneUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='primeiro_telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_telefone', to='usuarios.Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segundo_telefone', to='usuarios.Telefone'),
        ),
    ]
