# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:46
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0013_telefoneusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Telefone',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'tipo', models.CharField(choices=[(u'FIXO', u'FIXO'), (u'CELULAR', u'CELULAR')], max_length=7, verbose_name=u'Tipo Telefone')),
                (u'ddd', models.CharField(max_length=2, verbose_name=u'DDD')),
                (u'numero', models.CharField(max_length=10, verbose_name=u'Número')),
                (u'principal', models.CharField(choices=[(False, u'Não'), (True, u'Sim')], max_length=10, verbose_name=u'Telefone Principal?')),
            ],
            options={
                u'verbose_name': u'Telefone',
                u'verbose_name_plural': u'Telefones',
            },
        ),
        migrations.RemoveField(
            model_name=u'telefoneusuario',
            name=u'usuario',
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'cargo',
            field=models.CharField(default=u'--------', max_length=30, verbose_name=u'Cargo'),
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'casa_legislativa',
            field=models.CharField(default=u'--------', max_length=30, verbose_name=u'Casa Legislativa'),
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'cpf',
            field=models.CharField(default=u'00000000000', max_length=11, verbose_name=u'CPF'),
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'rg',
            field=models.CharField(max_length=9, null=True, verbose_name=u'RG'),
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'vinculo',
            field=models.CharField(choices=[(u'Tercerizado', u'Tercerizado'), (u'Efetivo', u'Efetivo'), (u'Contratado', u'Contratado')], default=u'--------', max_length=10, verbose_name=u'Vinculo'),
        ),
        migrations.DeleteModel(
            name=u'TelefoneUsuario',
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'primeiro_telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name=u'primeiro_telefone', to=u'usuarios.Telefone'),
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'segundo_telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name=u'segundo_telefone', to=u'usuarios.Telefone'),
        ),
    ]
