# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20160602_1503'),
        ('usuarios', '0013_auto_20160603_0816'),
    ]

    operations = [
    ]
