# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20160607_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='principal',
            field=models.CharField(choices=[(None, '----'), (False, 'Não'), (True, 'Sim')], max_length=10, verbose_name='Telefone Principal?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última atualização'),
        ),
    ]
