# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 16:23
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0014_auto_20160607_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'telefone',
            name=u'principal',
            field=models.CharField(choices=[(None, u'----'), (False, u'Não'), (True, u'Sim')], max_length=10, verbose_name=u'Telefone Principal?'),
        ),
        migrations.AlterField(
            model_name=u'usuario',
            name=u'data_ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=u'Última atualização'),
        ),
    ]
