# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20160603_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('can_change_conveniado', 'User can change conveniado field'), ('can_change_responsavel', 'User can change responsavel field')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
