# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 17:14
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0015_auto_20160607_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'usuario',
            name=u'vinculo',
            field=models.CharField(choices=[(u'Tercerizado', u'Tercerizado'), (u'Efetivo', u'Efetivo'), (u'Contratado', u'Contratado')], default=u'--------', max_length=30, verbose_name=u'Vinculo'),
        ),
    ]
