# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20160607_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(choices=[('Tercerizado', 'Tercerizado'), ('Efetivo', 'Efetivo'), ('Contratado', 'Contratado')], default='--------', max_length=30, verbose_name='Vinculo'),
        ),
    ]
