# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_telefoneusuario'),
        ('usuarios', '0017_usuario_grupo_usuario'),
    ]

    operations = [
    ]
