# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20160608_1138'),
        ('usuarios', '0016_auto_20160608_1414'),
    ]

    operations = [
    ]
