# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:27
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (u'usuarios', u'0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Servico',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'titulo', models.CharField(max_length=100, verbose_name=u'Título')),
                (u'descricao', models.TextField(verbose_name=u'Descrição')),
                (u'usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.UsuarioExterno')),
            ],
            options={
                u'verbose_name': u'Serviço',
                u'verbose_name_plural': u'Serviços',
            },
        ),
    ]
