# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 19:31
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0004_auto_20160531_1453'),
        (u'servicos', u'0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Sistema',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'sigla', models.CharField(max_length=10, verbose_name=u'Sigla')),
                (u'nome', models.CharField(max_length=100, verbose_name=u'Nome Sistema')),
            ],
            options={
                u'verbose_name': u'Sistema',
                u'verbose_name_plural': u'Sistemas',
            },
        ),
        migrations.CreateModel(
            name=u'Ticket',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'codigo', models.PositiveIntegerField()),
                (u'titulo', models.CharField(max_length=100, verbose_name=u'Título')),
                (u'resumo', models.CharField(max_length=50, verbose_name=u'Resumo')),
                (u'data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=u'Data de criação')),
                (u'data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name=u'Data de criação')),
                (u'descricao', models.TextField(blank=True, null=True, verbose_name=u'Descrição')),
                (u'sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'servicos.Sistema')),
                (u'usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.UsuarioExterno')),
            ],
            options={
                u'verbose_name': u'Ticket',
                u'verbose_name_plural': u'Tickets',
            },
        ),
        migrations.RemoveField(
            model_name=u'servico',
            name=u'usuario',
        ),
        migrations.DeleteModel(
            name=u'Servico',
        ),
    ]
