# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 19:48
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'servicos', u'0002_auto_20160531_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name=u'sistema',
            name=u'descricao',
            field=models.TextField(blank=True, null=True, verbose_name=u'Descrição'),
        ),
    ]
