# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 12:47
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (u'servicos', u'0003_sistema_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'ticket',
            name=u'usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.Usuario'),
        ),
    ]
