# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20160602_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='data_fechamento',
        ),
    ]
