# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20160602_1503'),
        ('servicos', '0005_remove_ticket_data_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.CharField(max_length=50, verbose_name='Resumo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Sistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'Solicitação de Novo Serviço',
                'verbose_name_plural': 'Solicitações de Novos Serviços',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sistema',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
