# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:26
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0012_auto_20160602_1503'),
        (u'servicos', u'0005_remove_ticket_data_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Solicitacao',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'codigo', models.PositiveIntegerField(unique=True)),
                (u'titulo', models.CharField(max_length=100, verbose_name=u'Título')),
                (u'resumo', models.CharField(max_length=50, verbose_name=u'Resumo')),
                (u'data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=u'Data de criação')),
                (u'descricao', models.TextField(blank=True, null=True, verbose_name=u'Descrição')),
                (u'sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'servicos.Sistema')),
                (u'usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'usuarios.Usuario')),
            ],
            options={
                u'verbose_name': u'Solicitação de Novo Serviço',
                u'verbose_name_plural': u'Solicitações de Novos Serviços',
                u'ordering': [u'data_criacao'],
            },
        ),
        migrations.RemoveField(
            model_name=u'ticket',
            name=u'sistema',
        ),
        migrations.RemoveField(
            model_name=u'ticket',
            name=u'usuario',
        ),
        migrations.DeleteModel(
            name=u'Ticket',
        ),
    ]
