# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 13:22
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'servicos', u'0007_solicitacao_casa_legislativa'),
    ]

    operations = [
        migrations.AddField(
            model_name=u'solicitacao',
            name=u'email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=u'Email de contato'),
        ),
        migrations.AddField(
            model_name=u'solicitacao',
            name=u'telefone_contato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=u'Telefone de contato'),
        ),
    ]
