# -*- coding: utf-8 -*-
u"""
Django settings for atendimento project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
from __future__ import absolute_import
from decouple import config
from dj_database_url import parse as db_url
from unipath import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).ancestor(2)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(u'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config(u'DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [u'*']

LOGIN_REDIRECT_URL = u'/'
LOGIN_URL = u'/login/?next='

# Application definition

ATENDIMENTO_APPS = [
    u'servicos',
    u'usuarios',
]

INSTALLED_APPS = [
    u'django.contrib.admin',
    u'django.contrib.auth',
    u'django.contrib.contenttypes',
    u'django.contrib.sessions',
    u'django.contrib.messages',
    u'django.contrib.staticfiles',

    # extra apps
    u'bootstrap3',
    u'captcha',
    u'crispy_forms',
    u'djangobower',
    u'django_extensions',
    u'floppyforms',
    u'sass_processor',
] + ATENDIMENTO_APPS

if DEBUG:
    INSTALLED_APPS += (u'debug_toolbar',)

MIDDLEWARE_CLASSES = [
    u'django.middleware.security.SecurityMiddleware',
    u'django.contrib.sessions.middleware.SessionMiddleware',
    u'django.middleware.common.CommonMiddleware',
    u'django.middleware.csrf.CsrfViewMiddleware',
    u'django.contrib.auth.middleware.AuthenticationMiddleware',
    u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    u'django.contrib.messages.middleware.MessageMiddleware',
    u'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = u'atendimento.urls'

TEMPLATES = [
    {
        u'BACKEND': u'django.template.backends.django.DjangoTemplates',
        u'DIRS': [u'templates'],
        u'APP_DIRS': True,
        u'OPTIONS': {
            u'context_processors': [
                u'django.template.context_processors.debug',
                u'django.template.context_processors.request',
                u'django.contrib.auth.context_processors.auth',
                u'django.core.context_processors.media',
                u'django.core.context_processors.static',
                u'django.contrib.messages.context_processors.messages',
                u'atendimento.context_processors.usuario_context'
            ],
            u'debug': DEBUG
        },
    },
]

WSGI_APPLICATION = u'atendimento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    u'default': config(
        u'DATABASE_URL',
        cast=db_url,
    )
}

# Email
EMAIL_USE_TLS = config(u'EMAIL_USE_TLS', cast=bool)
EMAIL_HOST = config(u'EMAIL_HOST', cast=unicode)
EMAIL_HOST_USER = config(u'EMAIL_HOST_USER', cast=unicode)
EMAIL_HOST_PASSWORD = config(u'EMAIL_HOST_PASSWORD', cast=unicode)
EMAIL_PORT = config(u'EMAIL_PORT', cast=int)
EMAIL_SEND_USER = config(u'EMAIL_SEND_USER', cast=unicode)

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        u'NAME': u'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        u'NAME': u'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        u'NAME': u'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        u'NAME': u'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# captcha config
CAPTCHA_IMAGE_SIZE = (130, 30)
CAPTCHA_FONT_SIZE = 30

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = u'pt-br'
LANGUAGES = (
    (u'pt-br', u'Português'),
)

TIME_ZONE = u'America/Sao_Paulo'
USE_I18N = True
USE_L10N = False
USE_TZ = True
# DATE_FORMAT = 'N j, Y'
DATE_FORMAT = u'd/m/Y'
SHORT_DATE_FORMAT = u'd/m/Y'
DATE_INPUT_FORMATS = (u'%d/%m/%Y', u'%m-%d-%Y', u'%Y-%m-%d')

LOCALE_PATHS = (
    u'locale',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = u'/static/'
STATIC_ROOT = BASE_DIR.child(u"collected_static")
STATICFILES_DIRS = (BASE_DIR.child(u"static"),)
STATICFILES_FINDERS = (
    u'django.contrib.staticfiles.finders.FileSystemFinder',
    u'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    u'djangobower.finders.BowerFinder',
    u'sass_processor.finders.CssFinder',
)

MEDIA_ROOT = BASE_DIR.child(u"media")
MEDIA_URL = u'/media/'

CRISPY_TEMPLATE_PACK = u'bootstrap3'
CRISPY_ALLOWED_TEMPLATE_PACKS = u'bootstrap3'
CRISPY_FAIL_SILENTLY = not DEBUG

BOWER_COMPONENTS_ROOT = BASE_DIR.child(u"bower")
BOWER_INSTALLED_APPS = (
    u'bootstrap-sass#3.3.6',
    u'components-font-awesome#4.5.0',
    u'tinymce#4.3.3',
    u'jquery-ui#1.11.4',
    u'jquery-runner#2.3.3',
    u'jQuery-Mask-Plugin#1.13.4',
    u'jsdiff#2.2.1',
)

# Additional search paths for SASS files when using the @import statement
SASS_PROCESSOR_INCLUDE_DIRS = (BOWER_COMPONENTS_ROOT.child(
    u'bower_components', u'bootstrap-sass', u'assets', u'stylesheets'),
)
