# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20160602_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='habilitado',
            field=models.CharField(choices=[(True, 'Sim'), (False, 'Não')], max_length=3, verbose_name='Habilitado?'),
        ),
    ]
