# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20160602_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
