# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20160602_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Criação'),
        ),
    ]
